### ISSUE TITLE
Error when importing clips with only 1 frame // undefined framerate?

### ISSUE THREAD

**Issue by LightArrowsEXE** [Endilll/vapoursynth-preview#6] opened 2020-06-18 00:41 UTC
When trying to import a clip with only 1 frame or a framerate that it can't read, vs-preview will error. The clip in question is a 1-frame m2ts file containing artwork, linked [here](https://files.catbox.moe/qgyt2q.m2ts). As can be seen in the [full mediainfo](https://pastebin.com/G0kyqnbG), it does appear to have a set framerate, but it's improperly tagged both in at least vsedit.

This error occurs simply when opening up the file straight after importing it. It outputs correctly when forcibly setting a framerate (like with `std.AssumeFPS`, for instance).

Expected behaviour would be for it to load with a framerate of 0/0, [like vsedit does](https://files.catbox.moe/a2dsc5.png), or return a clip with the properly tagged framerate.

vscode returns the following error:
```py
Exception has occurred: ZeroDivisionError
float division by zero
  File "<snip>\vapoursynth-preview\vspreview\core\types.py", line 853, in _calculate_seconds
    return frame_num / self.fps
  File "<snip>\vapoursynth-preview\vspreview\core\types.py", line 866, in to_time_interval
    seconds=self._calculate_seconds(int(frame_interval)))
  File "<snip>\vapoursynth-preview\vspreview\core\types.py", line 719, in __init__
    self.total_time   = self.to_time_interval(self.total_frames
  File "<snip>\vapoursynth-preview\vspreview\models\outputs.py", line 33, in __init__
    output = Output(vs_output, i)
  File "<snip>\vapoursynth-preview\vspreview\main.py", line 200, in rescan_outputs
    self.outputs = Outputs()
  File "<snip>\vapoursynth-preview\vspreview\main.py", line 513, in load_script
    self.toolbars.main.rescan_outputs()
  File "<snip>\vapoursynth-preview\vspreview\main.py", line 765, in main
    main_window.load_script(script_path, external_args=args.external_args)
  File "<snip>\vapoursynth-preview\run.py", line 4, in <module>
    main()
```

**Comment by Endilll** [comment] 2020-06-19 10:31
Thank you for the bug report.

I think the root of the issue is your source filter erroneously reporting 0 FPS numerator, therefore it should be fixed upstream. I've also tested few source filters: L-SMASH is reporting 0/0, and FFMS2 is reporting 90000/1. Sadly, I don't have DGIndex to test it, too.

The reason VSEdit works fine with FPS numerator 0 is that it has logic in place to deal with variable frame rate. Unfortunately, VSPreview doesn't have one (yet).

**Comment by LightArrowsEXE** [comment] 2020-06-19 16:14
Thanks for the response. Is it planned to become a feature in the near future, or is it best to stick with vsedit for those particular cases?

**Comment by Endilll** [comment] 2020-06-19 17:20
You should stick with VSEdit for now when you need true VFR. For this particular case I think `AssumeFPS` is a good workaround at the right place (user script).

I've been planning full-fledged VFR support (seeking by timepoint included) since before VSPreview went public. Not just to make it convenient for users, but also to keep parts of the implementation that rely on seeking by timepoint clean. But this would require support from other parts of the "stack", namely source filters and VapourSynth itself. I'm reluctant to engage myself into this, because I already have negative experience maintaining my fork of VapourSynth for almost a year (and counting) on behalf of users.

Supporting VFR to the extent of VSEdit is technically possible in VSPreview alone, but it's yet to be evaluated if it can be done in a clean enough way.

**Comment by Endilll** [comment] 2020-07-02 10:54
Opened a separate issue for VFR support.

**Closed by Endilll** 2020-07-02 10:54 UTC
